spring:
  application:
    name: api-gateway
server:
  port: 5555
  
# routes to url
#zuul:
#  routes:
#    api-a-url:
#      path: /api-a-url/**
#      url: http://localhost:2222/
      
#routes to eureka
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-A
    api-b:
     path: /api-b/**
     serviceId: service-B
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  