spring:
  application:
    name: bar
logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG

#zipkin地址，Sleuth会将trace数据以http的方式发送，采样率percentage=1意味着100%发送
#sleuth也会产生性能消耗，因此percentage=1只是为了方便调试用例，生产环境下根据需要配置
spring.zipkin.base-url: http://localhost:9411
spring.sleuth.sampler.percentage: 1