#==================================================#
#=================spring boot 配置==================#
#==================================================#
spring:
  application:
    name: udmp-eureka-client
#==================================================#
#===================erueka配置======================#
#==================================================#
eureka:
  client:
    serviceUrl:
      #默认的eureka服务器地址 
      defaultZone: http://localhost:8761/eureka/
#==================================================#
#=================Embedded server 配置==============#
#==================================================#
server:
  port: 8009
